### ISSUE TITLE
logo for JuliaMatrices

### ISSUE THREAD

**Issue by mikolajhojda** [JuliaMatrices/InfiniteLinearAlgebra.jl#13]
![julia-matrics](https://user-images.githubusercontent.com/32071801/71233859-24ed0100-22f7-11ea-9ca9-85e985908772.png)
[submission.docx](https://github.com/JuliaMatrices/InfiniteLinearAlgebra.jl/files/3986935/submission.docx)

**Comment by logankilpatrick** [comment]
Hey @mikolajhojda, the Julia logo with the blue is actual the Julia Computing logo. It would be better to maybe have a 2-2 matrice of the 3 dot Julia logo.

**Comment by mikolajhojda** [comment]
![julia-matrics](https://user-images.githubusercontent.com/32071801/71260632-9cdd1a80-233b-11ea-9f3a-89a52a601a97.png)
[submission.docx](https://github.com/JuliaMatrices/InfiniteLinearAlgebra.jl/files/3988603/submission.docx)

**Comment by logankilpatrick** [comment]
@dlfivefifty can you update it to this one to reflect the Julia language rather than Julia computing? 

Great work @mikolajhojda !

**Comment by logankilpatrick** [comment]
Feel free to close this issue once the org logo has been updated.
